# Cambiamos a la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:gasolineraDB;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Le decimos a Hibernate que use el lenguaje de H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto hace que las tablas de tu base de datos se creen solitas al arrancar
spring.jpa.hibernate.ddl-auto=update

# (Opcional) Por si quieres ver una consola visual de tu base de datos en internet
spring.h2.console.enabled=true